hydra:
  run:
    dir: outputs/qa_inference/${now:%Y-%m-%d}/${now:%H-%M-%S}/graphrag_benchmark/${dataset_name}
  searchpath:
    - pkg://gfmrag.workflow.config

defaults:
  - _self_
  # Not used directly in the script but kept for consistency with other workflows.
  - qa_prompt: graphrag_benchmark/novel/fact_retrieval

seed: 1024
dataset_name: graphrag_benchmark_novel

llm:
  _target_: gfmrag.llms.ChatGPT
  model_name_or_path: gpt-4o-mini
  retry: 5

prompt_root: qa_prompt/graphrag_benchmark/novel

prompt_map:
  Fact Retrieval: ${prompt_root}/fact_retrieval
  Complex Reasoning: ${prompt_root}/complex_reasoning
  Contextual Summarize: ${prompt_root}/contextual_summary
  Creative Generation: ${prompt_root}/creative_generation

task_type:
  source: field
  field: question_type

test:
  n_sample: -1 # Number of samples to test, -1 means all samples
  top_k: 10
  n_threads: 10
  retrieved_result_path: null
  document_path: data/${dataset_name}/raw/documents.json
  prediction_result_path: null
